//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringCheckerService")]
public interface IStringCheckerService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCheckerService/CheckRepeatedCount", ReplyAction="http://tempuri.org/IStringCheckerService/CheckRepeatedCountResponse")]
    int CheckRepeatedCount(string lookIn, string lookFor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCheckerService/CheckRepeatedCount", ReplyAction="http://tempuri.org/IStringCheckerService/CheckRepeatedCountResponse")]
    System.Threading.Tasks.Task<int> CheckRepeatedCountAsync(string lookIn, string lookFor);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringCheckerServiceChannel : IStringCheckerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringCheckerServiceClient : System.ServiceModel.ClientBase<IStringCheckerService>, IStringCheckerService
{
    
    public StringCheckerServiceClient()
    {
    }
    
    public StringCheckerServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringCheckerServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringCheckerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringCheckerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int CheckRepeatedCount(string lookIn, string lookFor)
    {
        return base.Channel.CheckRepeatedCount(lookIn, lookFor);
    }
    
    public System.Threading.Tasks.Task<int> CheckRepeatedCountAsync(string lookIn, string lookFor)
    {
        return base.Channel.CheckRepeatedCountAsync(lookIn, lookFor);
    }
}
